<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="css/bulma.css">
<link rel="stylesheet" href="css/stylesheet.css">
<link rel="stylesheet" href="css/font-awesome.css">
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,400" rel="stylesheet">
<link rel="icon" href="images/icon.png">
<script type="text/javascript" src="js/scripts.js"></script>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
