<?php ?>
<header>
    <nav class="navbar">
        <div class="navbar-brand">
            <a class="navbar-item" href="index.php"><img style="max-height: 100%; width: 150px;" src="dlink_logo.png" /></a>
            <div class="navbar-burger" onclick="showMenu()" id="navbar-burger">
            <span></span>
            <span></span>
            <span></span>
        </div>
        </div>
        <div class="navbar-menu" id="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="plans.php">Internet Plans</a>
            <a class="navbar-item" href="coverage.php">Can I Get Service?</a>
            <a class="navbar-item" href="about.php">About Us</a>
            <a class="navbar-item" href="contact.php">Contact</a>
          </div>
          <div class="navbar-end">
            <a class="navbar-item" 
              href="https://secure7.userservices.net/csm_v7/?database=live&isprealm=deltalinknet.com&appuser_id=14360&key=1e28284f59e926547bb6793ad8723722" 
              target="_blank">Login</a>
              <div class="field is-grouped is-grouped-right">
                <div class="navbar-item">
                  <a href="https://twitter.com/DeltaLink_net" class="button" style=" border-color: rgba(0, 0, 0, 0); color: #1DA1F2;" data-show-count="false">
                    <span class="icon"><i class="fa fa-twitter" aria-hidden="true"></i></span>
                    </a>
                </div>
                <div class="navbar-item">
                  <a class="button is-outlined is-light" style="border-color: rgba(0, 0, 0, 0); color: #3B5998;">
                    <span class="icon"><i class="fa fa-facebook" aria-hidden="true"></i>
                    </span>
                    </a>
                </div>
              </div>
          </div>
        </div>
    </nav>
</header>